name: eternal_tie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  appinio_video_player: ^1.2.2
  cloudinary_public: ^0.23.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.8
  native_video_player: ^1.3.1
  provider: ^6.1.2
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  video_player: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
 